import { FormEvent, useEffect, useState } from 'react'; import { api, money } from '../api/client';
type Item={id:string;name:string;unit:string}; type Usage={inventoryItemId:string;quantity:string;inventoryItem:Item}; type Service={id:string;code:string;name:string;fee:string;active:boolean;displayOrder:number;inventoryUsage:Usage[]};
export function ServicesPage(){const[s,setS]=useState<Service[]>([]),[items,setItems]=useState<Item[]>([]);const[error,setError]=useState('');const load=()=>Promise.all([api<Service[]>('/services/all'),api<any[]>('/inventory')]).then(([a,b])=>{setS(a);setItems(b.map(x=>({id:x.id,name:x.name,unit:x.unit}))) }).catch(e=>setError(e.message));useEffect(()=>{ void load(); },[]);
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/services',{method:'POST',body:JSON.stringify({code:String(f.get('code')).toUpperCase(),name:String(f.get('name')),fee:String(f.get('fee')),displayOrder:Number(f.get('displayOrder')||0)})});e.currentTarget.reset();load()}catch(e){setError(e instanceof Error?e.message:'Failed')}}
async function toggle(x:Service){await api(`/services/${x.id}`,{method:'PATCH',body:JSON.stringify({active:!x.active})});load()}
async function edit(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/services/${id}`,{method:'PATCH',body:JSON.stringify({name:String(f.get('name')),fee:String(f.get('fee'))})});load()}catch(e){setError(e instanceof Error?e.message:'Failed')}}
async function addUsage(e:FormEvent<HTMLFormElement>,serviceId:string){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/services/${serviceId}/inventory-usage`,{method:'POST',body:JSON.stringify({inventoryItemId:String(f.get('inventoryItemId')),quantity:String(f.get('quantity'))})});e.currentTarget.reset();load()}catch(e){setError(e instanceof Error?e.message:'Failed')}}
async function removeUsage(serviceId:string,itemId:string){await api(`/services/${serviceId}/inventory-usage/${itemId}`,{method:'DELETE'});load()}
return <div className="page"><div className="page-title"><div><h1>Services Management</h1><p>Create services and define the consumables automatically deducted per service.</p></div></div>{error&&<div className="alert alert-danger">{error}</div>}<div className="card-estylo mb-4 form-card"><h5>Add Service</h5><form className="row g-2" onSubmit={create}><div className="col-md-3"><input className="form-control" name="code" placeholder="Code" required/></div><div className="col-md-4"><input className="form-control" name="name" placeholder="Service name" required/></div><div className="col-md-2"><input className="form-control" name="fee" inputMode="decimal" placeholder="Fee" required/></div><div className="col-md-1"><input className="form-control" name="displayOrder" type="number" defaultValue="0"/></div><div className="col-md-2"><button className="btn btn-estylo w-100">Add</button></div></form></div>{s.map(x=><div className="card-estylo mb-3" key={x.id}><div className="d-flex justify-content-between align-items-start gap-3"><div><h5>{x.name} <span className="muted">{x.code}</span></h5><div>{money(x.fee)} · {x.active?'Active':'Inactive'}</div></div><button className="btn btn-sm btn-outline-secondary" onClick={()=>toggle(x)}>{x.active?'Deactivate':'Activate'}</button></div><form className="row g-2 mt-2" onSubmit={e=>edit(e,x.id)}><div className="col-md-5"><input className="form-control form-control-sm" name="name" defaultValue={x.name}/></div><div className="col-md-3"><input className="form-control form-control-sm" name="fee" defaultValue={x.fee} inputMode="decimal"/></div><div className="col-md-2"><button className="btn btn-sm btn-outline-dark">Save Changes</button></div></form><hr/><div className="section-label text-dark">AUTOMATIC INVENTORY USAGE</div>{x.inventoryUsage.length===0?<p className="muted">No consumables configured.</p>:<div className="d-flex flex-wrap gap-2 mb-3">{x.inventoryUsage.map(u=><span className="badge text-bg-light border" key={u.inventoryItemId}>{u.inventoryItem.name}: {u.quantity} {u.inventoryItem.unit} <button className="btn btn-link btn-sm text-danger p-0 ms-2" onClick={()=>removeUsage(x.id,u.inventoryItemId)}>×</button></span>)}</div>}<form className="row g-2" onSubmit={e=>addUsage(e,x.id)}><div className="col-md-5"><select className="form-select" name="inventoryItemId" required><option value="">Select inventory item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} ({i.unit})</option>)}</select></div><div className="col-md-3"><input className="form-control" name="quantity" inputMode="decimal" placeholder="Qty per service" required/></div><div className="col-md-4"><button className="btn btn-outline-dark">Set Usage</button></div></form></div>)}</div>}
